#!/usr/bin/env bash
# smbios: generate + inject a persistent SMBIOS identity into OpenCore.qcow2
# (the prebuilt image ships placeholder serial W00000000001 — Apple's servers
# reject it, which breaks Apple ID sign-in). Loaded via bin/macos-vm after
# common.sh. Requires the VM to be stopped; uses qemu-nbd + sudo (the same
# pattern as ensure_ignore_msrs: prints what it runs).

set -euo pipefail

SMB_CONF="$DATA_DIR/smbios.conf"
SMB_MNT="$DATA_DIR/.smbios-mnt"
SMB_ORIG="$DATA_DIR/OpenCore.plist.pristine"
SMB_TMP="$DATA_DIR/config.plist.tmp"
SMB_PLIST="EFI/OC/config.plist"

# VMHide (Lilu plugin) hides kern.hv_vmm_present from Apple ID processes —
# macOS 15+ blocks sign-in on any VM, SMBIOS notwithstanding. Pinned versions:
# VMHide 2.0.0 (Tahoe support), Lilu 1.7.2 (VMHide needs >= 1.7.0; the
# vendored OpenCore ships 1.6.8).
VMHIDE_DIR="$DATA_DIR/vmhide"
VMHIDE_LILU_ZIP="https://github.com/acidanthera/Lilu/releases/download/1.7.2/Lilu-1.7.2-RELEASE.zip"
VMHIDE_ZIP="https://github.com/Carnations-Botanica/VMHide/releases/download/2.0.0/VMHide-2.0.0-RELEASE.zip"

smbios_conf_field() { # name -> value ("" if absent)
  [ -f "$SMB_CONF" ] || return 0
  sed -n "s/^$1=//p" "$SMB_CONF" | tail -1
}

smbios_rom() { # MAC-derived ROM (hex, no separators)
  printf '%s' "${MAC//:/}"
}

smbios_desired() { # echo "MODEL|SERIAL|MLB|UUID|ROM" (env/conf overrides win)
  # Serial and MLB encode the model — when the model changes (or is overridden)
  # and no explicit serial/MLB is given, drop the inherited ones so the python
  # side generates a fresh pair for the new model.
  local conf_model model serial mlb uuid rom
  conf_model="$(smbios_conf_field SMBIOS_MODEL)"
  model="${SMBIOS_MODEL:-$conf_model}"
  [ -n "$model" ] || model=iMac19,1
  serial="${SMBIOS_SERIAL:-}"
  mlb="${SMBIOS_MLB:-}"
  if [ -z "$serial" ] && { [ -z "$SMBIOS_MODEL" ] || [ "$SMBIOS_MODEL" = "$conf_model" ]; }; then
    serial="$(smbios_conf_field SMBIOS_SERIAL)"
  fi
  if [ -z "$mlb" ] && { [ -z "$SMBIOS_MODEL" ] || [ "$SMBIOS_MODEL" = "$conf_model" ]; }; then
    mlb="$(smbios_conf_field SMBIOS_MLB)"
  fi
  uuid="${SMBIOS_UUID:-$(smbios_conf_field SMBIOS_UUID)}"
  rom="$(smbios_conf_field SMBIOS_ROM)"
  [ -n "$rom" ] || rom="$(smbios_rom)"
  printf '%s|%s|%s|%s|%s' "$model" "$serial" "$mlb" "$uuid" "$rom"
}

smbios_write_conf() { # "$SERIAL|$MLB|$UUID|$MODEL|$ROM" (python order)
  IFS='|' read -r serial mlb uuid model rom <<<"$1"
  {
    echo "# Generated by macos-vm — this identity is unique to this VM."
    echo "# Do not copy this file to another VM/host (duplicate identities"
    echo "# look like device farming to Apple)."
    echo "SMBIOS_MODEL=$model"
    echo "SMBIOS_SERIAL=$serial"
    echo "SMBIOS_MLB=$mlb"
    echo "SMBIOS_UUID=$uuid"
    echo "SMBIOS_ROM=$rom"
    echo "SMBIOS_MAC=$MAC"
    echo "SMBIOS_VMHIDE=1"
    echo "SMBIOS_CREATED=$(date +%F)"
  } > "$SMB_CONF"
}

vmhide_fetch() { # download + extract Lilu/VMHide kexts (idempotent, pinned)
  [ -d "$VMHIDE_DIR/Lilu.kext" ] && [ -d "$VMHIDE_DIR/VMHide.kext" ] && return 0
  mkdir -p "$VMHIDE_DIR"
  local z
  for z in "$VMHIDE_LILU_ZIP" "$VMHIDE_ZIP"; do
    [ -f "$VMHIDE_DIR/$(basename "$z")" ] || {
      log "fetching $(basename "$z")"
      curl -fsSL --retry 3 -o "$VMHIDE_DIR/$(basename "$z")" "$z" \
        || die "failed to fetch $(basename "$z") — network?"
    }
  done
  log "extracting Lilu + VMHide kexts"
  python3 - "$VMHIDE_DIR" <<'PYEOF'
import sys, zipfile
d = sys.argv[1]
for name in ("Lilu.kext", "VMHide.kext"):
    for z in ("Lilu-1.7.2-RELEASE.zip", "VMHide-2.0.0-RELEASE.zip"):
        path = d + "/" + z
        with zipfile.ZipFile(path) as zf:
            hits = [i for i in zf.infolist() if i.filename.startswith(name + "/")]
            if hits:
                zf.extractall(d, hits)
                break
    else:
        raise SystemExit("kext %s not in its zip" % name)
PYEOF
  [ -d "$VMHIDE_DIR/Lilu.kext" ] && [ -d "$VMHIDE_DIR/VMHide.kext" ] \
    || die "kext extraction failed in $VMHIDE_DIR"
}

vmhide_sync() { # copy Lilu + VMHide into the mounted ESP's Kexts dir
  local kexts="$SMB_MNT/EFI/OC/Kexts"
  [ -d "$kexts" ] || die "$kexts missing in OpenCore image"
  sudo rm -rf "$kexts/Lilu.kext" "$kexts/VMHide.kext"
  sudo cp -r "$VMHIDE_DIR/Lilu.kext" "$VMHIDE_DIR/VMHide.kext" "$kexts/"
  log "kexts synced: Lilu + VMHide in $kexts"
}

smbios_nbd_connect() { # pick a free /dev/nbdN, connect OpenCore.qcow2
  require qemu-nbd "apt install qemu-utils"
  if [ ! -e /dev/nbd0 ]; then
    log "loading nbd kernel module (sudo)"
    sudo modprobe nbd max_part=8 2>/dev/null || true
  fi
  local d
  for d in $(seq 0 15); do
    [ -e "/dev/nbd$d" ] && [ ! -e "/sys/block/nbd$d/pid" ] || continue
    log "connecting $OPEN_CORE to /dev/nbd$d (sudo)"
    sudo qemu-nbd --connect="/dev/nbd$d" "$OPEN_CORE"
    echo "/dev/nbd$d"
    return 0
  done
  die "no free nbd device — load the module first: sudo modprobe nbd max_part=8"
}

smbios_cleanup() { # unmount (flushes writes) THEN disconnect — order matters
  sudo umount "$SMB_MNT" 2>/dev/null || true
  [ -z "${SMB_NBD:-}" ] || sudo qemu-nbd --disconnect "$SMB_NBD" >/dev/null 2>&1 || true
}

smbios_teardown() { # explicit cleanup (mounts must be gone before qemu boots)
  trap - EXIT
  smbios_cleanup
}

smbios_mount_open_core() { # connect + mount; sets SMB_NBD/SMB_MNT; EXIT trap cleans up
  local nbd part i
  nbd="$(smbios_nbd_connect)"
  SMB_NBD="$nbd"
  trap smbios_cleanup EXIT
  part="$nbd"
  for i in $(seq 1 20); do
    [ -e "${nbd}p1" ] && { part="${nbd}p1"; break; }
    sleep 0.5
  done
  [ -e "$part" ] || die "partition ${nbd}p1 never appeared (modprobe nbd max_part=8)"
  mkdir -p "$SMB_MNT"
  log "mounting $part (sudo)"
  sudo mount "$part" "$SMB_MNT"
}

smbios_inject() { # mount, compare, generate/persist identity, write plist
  vm_running && die "stop the VM before touching the SMBIOS"
  [ -f "$OPEN_CORE" ] || return 0
  local cur_serial cur_mlb cur_model cur_rom
  smbios_mount_open_core
  rm -f "$SMB_TMP"
  sudo cp "$SMB_MNT/$SMB_PLIST" "$SMB_TMP"
  sudo chown "$(id -un)" "$SMB_TMP"

  if [ ! -f "$SMB_ORIG" ]; then
    sudo cp "$SMB_MNT/$SMB_PLIST" "$SMB_ORIG"
    log "backed up pristine plist to $SMB_ORIG"
  fi

  IFS='|' read -r cur_serial cur_mlb cur_uuid cur_model cur_rom <<<"$(python3 "$ROOT/lib/smbios.py" show "$SMB_TMP")"
  IFS='|' read -r want_model want_serial want_mlb want_uuid want_rom <<<"$(smbios_desired)"

  local out
  if [ ! -f "$SMB_CONF" ] && [ -n "$cur_serial" ] && [ "$cur_serial" != "W00000000001" ] \
     && [ -z "$SMBIOS_SERIAL" ] && [ "$cur_model" = "$want_model" ]; then
    log "keeping existing identity from the plist (serial $cur_serial)"
    out="$cur_serial|$cur_mlb|$cur_uuid|$cur_model|$cur_rom"
  elif [ -n "$cur_serial" ] && [ "$cur_serial" = "$want_serial" ] && [ "$cur_model" = "$want_model" ] \
       && [ -z "$SMBIOS_SERIAL" ] && [ -z "$SMBIOS_MLB" ] && [ -z "$SMBIOS_UUID" ]; then
    log "SMBIOS already injected ($cur_serial) — nothing to do"
    out="$cur_serial|$cur_mlb|$cur_uuid|$cur_model|$cur_rom"
  else
    if [ -n "$want_serial" ] || [ -n "$want_mlb" ]; then
      log "applying $want_model identity from overrides"
    else
      log "generating a fresh $want_model identity (macserial algorithm)"
    fi
    out="$(python3 "$ROOT/lib/smbios.py" inject "$SMB_TMP" --model "$want_model" --rom "$want_rom" \
      ${want_serial:+--serial "$want_serial"} ${want_mlb:+--mlb "$want_mlb"} ${want_uuid:+--uuid "$want_uuid"})"
  fi
  if [ "$(smbios_conf_field SMBIOS_VMHIDE)" != 1 ]; then
    vmhide_fetch
    python3 "$ROOT/lib/smbios.py" kextadd "$SMB_TMP"
    vmhide_sync
  fi
  sudo cp "$SMB_TMP" "$SMB_MNT/$SMB_PLIST"
  log "wrote $SMB_MNT/$SMB_PLIST"
  smbios_write_conf "$out"
  smbios_teardown
  smbios_verify "$out"
  log "SMBIOS identity: $out"
}

smbios_verify() { # re-mount read-only and confirm the write persisted
  local want="$1" got
  smbios_mount_open_core
  got="$(python3 "$ROOT/lib/smbios.py" show "$SMB_MNT/$SMB_PLIST")"
  [ -d "$SMB_MNT/EFI/OC/Kexts/VMHide.kext" ] \
    || die "VMHide.kext missing from the image after injection"
  smbios_teardown
  if [ "$got" != "$want" ]; then
    die "injection did not persist (plist shows $got) — the qcow2 was not updated"
  fi
}

smbios_ensure() { # called on every `run`; no-op when identity is in place
  [ -f "$OPEN_CORE" ] || return 0
  [ -f "$SMB_CONF" ] || { smbios_inject; return; }
  IFS='|' read -r want_model want_serial _ _ want_rom <<<"$(smbios_desired)"
  local have_model have_serial have_rom
  have_model="$(smbios_conf_field SMBIOS_MODEL)"
  have_serial="$(smbios_conf_field SMBIOS_SERIAL)"
  have_rom="$(smbios_conf_field SMBIOS_ROM)"
  if [ "$have_model" = "$want_model" ] && [ -z "${SMBIOS_SERIAL:-}" ] \
     && [ "$have_serial" = "$want_serial" ] && [ -z "${SMBIOS_MLB:-}" ] \
     && [ -z "${SMBIOS_UUID:-}" ] && [ "$have_rom" = "$want_rom" ] \
     && [ "$(smbios_conf_field SMBIOS_VMHIDE)" = 1 ]; then
    return 0
  fi
  smbios_inject
}

cmd_smbios() {
  case "${1:-}" in
    show)
      vm_running && die "stop the VM first (smbios show mounts the OpenCore image)"
      [ -f "$OPEN_CORE" ] || die "OpenCore image missing — run 'macos-vm check' to fetch it"
      smbios_mount_open_core
      local out
      out="$(python3 "$ROOT/lib/smbios.py" show "$SMB_MNT/$SMB_PLIST")"
      IFS='|' read -r serial mlb uuid model rom <<<"$out"
      printf '%-14s %s\n' "model" "$model"
      printf '%-14s %s\n' "serial" "$serial"
      printf '%-14s %s\n' "MLB" "$mlb"
      printf '%-14s %s\n' "UUID" "$uuid"
      printf '%-14s %s\n' "ROM" "$rom"
      if [ -f "$SMB_CONF" ]; then
        printf '%-14s %s\n' "conf serial" "$(smbios_conf_field SMBIOS_SERIAL)"
        [ "$(smbios_conf_field SMBIOS_SERIAL)" = "$serial" ] \
          && echo "state: in sync" || echo "state: DRIFT — plist differs from $SMB_CONF"
      else
        echo "state: no $SMB_CONF yet"
      fi
      smbios_teardown
      ;;
    generate|set)
      if [ "${1:-}" = set ]; then
        local serial="${2:-}" mlb="${3:-}" uuid="${4:-}" model="${5:-$SMBIOS_MODEL}"
        [ -n "$serial" ] && [ -n "$mlb" ] || die "usage: macos-vm smbios set SERIAL MLB UUID [MODEL]"
        [ "$ALLOW_REAL_SERIAL" = 1 ] || die "refusing to set a serial manually — a real machine's serial is the #1 Apple account-flag vector. Re-run with ALLOW_REAL_SERIAL=1 if you know what you're doing."
        warn "manual serial override — make sure this serial is not registered to a real machine"
        python3 "$ROOT/lib/smbios.py" info --serial "$serial" --model "$model" >/dev/null \
          || die "serial does not decode for $model"
        python3 "$ROOT/lib/smbios.py" verify-mlb "$mlb" >/dev/null || die "MLB checksum invalid"
        SMBIOS_SERIAL="$serial" SMBIOS_MLB="$mlb" SMBIOS_UUID="$uuid" SMBIOS_MODEL="$model" smbios_inject
      else
        smbios_inject
      fi
      ;;
    check)
      vm_running && die "stop the VM first"
      [ -f "$SMB_CONF" ] || die "no identity yet — run 'macos-vm run' once (or 'macos-vm smbios generate')"
      log "advisory checks against Apple's servers (network + rate limits apply):"
      python3 "$ROOT/lib/smbios.py" check \
        --serial "$(smbios_conf_field SMBIOS_SERIAL)" \
        --mlb "$(smbios_conf_field SMBIOS_MLB)" \
        --model "$(smbios_conf_field SMBIOS_MODEL)"
      echo "the authoritative test is Apple ID sign-in inside the VM"
      ;;
    reset)
      vm_running && die "stop the VM first"
      log "removing injected SMBIOS and re-fetching the pristine OpenCore image"
      rm -f "$OPEN_CORE" "$SMB_CONF" "$SMB_ORIG" "$SMB_TMP"
      rm -rf "$SMB_MNT"
      ensure_assets
      log "OpenCore restored — next 'macos-vm run' generates a fresh identity"
      ;;
    *)
      die "usage: macos-vm smbios {show|generate|set SERIAL MLB UUID [MODEL]|check|reset}"
      ;;
  esac
}
